function mpli_header( filename, x, y )

% Generates a C-file that compiles into an array of coefficients sutiable
% for a interpolated linearization algorithm

% See examples\profile\profile_flowbody.m for an example of how to generate
% the 'coefs' argument.  

    f = fopen( filename, 'wt' );
    len = length(x);
    fprintf( f, '// This file is auto-generated by coef_header.m\n\n' );
    fprintf( f, 'static const mpli_point_t s_flow_comp[%d] =\n{\n', len );
    for i=1:len
        fprintf( f, '\t{ %.12g, %.12g },\n', x(i), y(i) );
    end
    fprintf( f, '};\n\n');
    fprintf( f, 'static const mpli_t s_mpli_flow_comp =\n{\n\ts_flow_comp, %d\n};\n', len );
    fclose(f);
end
